"""empty message

Revision ID: 154a5a194303
Revises: cdb99e36b560
Create Date: 2024-06-23 19:46:07.063781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154a5a194303'
down_revision = 'cdb99e36b560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('post_office', sa.String(length=60), nullable=False),
    sa.Column('preferences', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
